package com.scholastic.sbam.server.database.codegen;

// Generated Jun 14, 2011 5:14:03 PM by Hibernate Tools 3.2.4.GA

/**
 * AeAu generated by hbm2java
 */
public class AeAu implements java.io.Serializable {

	private AeAuId id;
	private String parent;
	private String soldTo;
	private String shipTo;
	private String goLocCode;

	public AeAu() {
	}

	public AeAu(AeAuId id, String parent, String soldTo, String shipTo,
			String goLocCode) {
		this.id = id;
		this.parent = parent;
		this.soldTo = soldTo;
		this.shipTo = shipTo;
		this.goLocCode = goLocCode;
	}

	public AeAuId getId() {
		return this.id;
	}

	public void setId(AeAuId id) {
		this.id = id;
	}

	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getSoldTo() {
		return this.soldTo;
	}

	public void setSoldTo(String soldTo) {
		this.soldTo = soldTo;
	}

	public String getShipTo() {
		return this.shipTo;
	}

	public void setShipTo(String shipTo) {
		this.shipTo = shipTo;
	}

	public String getGoLocCode() {
		return this.goLocCode;
	}

	public void setGoLocCode(String goLocCode) {
		this.goLocCode = goLocCode;
	}

}
