package com.scholastic.sbam.server.database.codegen;

// Generated Jul 28, 2011 1:20:31 PM by Hibernate Tools 3.2.4.GA

/**
 * AeAuId generated by hbm2java
 */
public class AeAuId implements java.io.Serializable {

	private int aeId;
	private int auId;

	public AeAuId() {
	}

	public AeAuId(int aeId, int auId) {
		this.aeId = aeId;
		this.auId = auId;
	}

	public int getAeId() {
		return this.aeId;
	}

	public void setAeId(int aeId) {
		this.aeId = aeId;
	}

	public int getAuId() {
		return this.auId;
	}

	public void setAuId(int auId) {
		this.auId = auId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AeAuId))
			return false;
		AeAuId castOther = (AeAuId) other;

		return (this.getAeId() == castOther.getAeId())
				&& (this.getAuId() == castOther.getAuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAeId();
		result = 37 * result + this.getAuId();
		return result;
	}

}
