package com.scholastic.sbam.server.database.codegen;

// Generated Jul 4, 2011 7:39:15 PM by Hibernate Tools 3.2.4.GA

/**
 * AePref generated by hbm2java
 */
public class AePref implements java.io.Serializable {

	private AePrefId id;
	private String prefValue;

	public AePref() {
	}

	public AePref(AePrefId id, String prefValue) {
		this.id = id;
		this.prefValue = prefValue;
	}

	public AePrefId getId() {
		return this.id;
	}

	public void setId(AePrefId id) {
		this.id = id;
	}

	public String getPrefValue() {
		return this.prefValue;
	}

	public void setPrefValue(String prefValue) {
		this.prefValue = prefValue;
	}

}
