package com.scholastic.sbam.server.database.codegen;

// Generated Jun 14, 2011 5:14:03 PM by Hibernate Tools 3.2.4.GA

/**
 * AeRsurl generated by hbm2java
 */
public class AeRsurl implements java.io.Serializable {

	private AeRsurlId id;

	public AeRsurl() {
	}

	public AeRsurl(AeRsurlId id) {
		this.id = id;
	}

	public AeRsurlId getId() {
		return this.id;
	}

	public void setId(AeRsurlId id) {
		this.id = id;
	}

}
