package com.scholastic.sbam.server.database.codegen;

// Generated Oct 14, 2011 9:50:42 AM by Hibernate Tools 3.2.4.GA

/**
 * AeUrl generated by hbm2java
 */
public class AeUrl implements java.io.Serializable {

	private AeUrlId id;
	private char remote;

	public AeUrl() {
	}

	public AeUrl(AeUrlId id, char remote) {
		this.id = id;
		this.remote = remote;
	}

	public AeUrlId getId() {
		return this.id;
	}

	public void setId(AeUrlId id) {
		this.id = id;
	}

	public char getRemote() {
		return this.remote;
	}

	public void setRemote(char remote) {
		this.remote = remote;
	}

}
