package com.scholastic.sbam.server.database.codegen;

// Generated Jul 28, 2011 1:20:31 PM by Hibernate Tools 3.2.4.GA

/**
 * AeUrl generated by hbm2java
 */
public class AeUrl implements java.io.Serializable {

	private AeUrlId id;
	private char remote;

	public AeUrl() {
	}

	public AeUrl(AeUrlId id, char remote) {
		this.id = id;
		this.remote = remote;
	}

	public AeUrlId getId() {
		return this.id;
	}

	public void setId(AeUrlId id) {
		this.id = id;
	}

	public char getRemote() {
		return this.remote;
	}

	public void setRemote(char remote) {
		this.remote = remote;
	}

}
