package com.scholastic.sbam.server.database.codegen;

// Generated Mar 3, 2011 5:21:42 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Agreement generated by hbm2java
 */
public class Agreement implements java.io.Serializable {

	private Integer id;
	private int idCheckDigit;
	private int billUcn;
	private String billUcnSuffix;
	private String agreementTypeCode;
	private String commissionCode;
	private String deleteReasonCode;
	private Date createdDatetime;
	private char status;

	public Agreement() {
	}

	public Agreement(int idCheckDigit, int billUcn, String billUcnSuffix,
			String agreementTypeCode, String commissionCode,
			String deleteReasonCode, Date createdDatetime, char status) {
		this.idCheckDigit = idCheckDigit;
		this.billUcn = billUcn;
		this.billUcnSuffix = billUcnSuffix;
		this.agreementTypeCode = agreementTypeCode;
		this.commissionCode = commissionCode;
		this.deleteReasonCode = deleteReasonCode;
		this.createdDatetime = createdDatetime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdCheckDigit() {
		return this.idCheckDigit;
	}

	public void setIdCheckDigit(int idCheckDigit) {
		this.idCheckDigit = idCheckDigit;
	}

	public int getBillUcn() {
		return this.billUcn;
	}

	public void setBillUcn(int billUcn) {
		this.billUcn = billUcn;
	}

	public String getBillUcnSuffix() {
		return this.billUcnSuffix;
	}

	public void setBillUcnSuffix(String billUcnSuffix) {
		this.billUcnSuffix = billUcnSuffix;
	}

	public String getAgreementTypeCode() {
		return this.agreementTypeCode;
	}

	public void setAgreementTypeCode(String agreementTypeCode) {
		this.agreementTypeCode = agreementTypeCode;
	}

	public String getCommissionCode() {
		return this.commissionCode;
	}

	public void setCommissionCode(String commissionCode) {
		this.commissionCode = commissionCode;
	}

	public String getDeleteReasonCode() {
		return this.deleteReasonCode;
	}

	public void setDeleteReasonCode(String deleteReasonCode) {
		this.deleteReasonCode = deleteReasonCode;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
