package com.scholastic.sbam.server.database.codegen;

// Generated Mar 7, 2011 3:54:30 PM by Hibernate Tools 3.2.4.GA

/**
 * AgreementTermId generated by hbm2java
 */
public class AgreementTermId implements java.io.Serializable {

	private int agreementId;
	private int id;

	public AgreementTermId() {
	}

	public AgreementTermId(int agreementId, int id) {
		this.agreementId = agreementId;
		this.id = id;
	}

	public int getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(int agreementId) {
		this.agreementId = agreementId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgreementTermId))
			return false;
		AgreementTermId castOther = (AgreementTermId) other;

		return (this.getAgreementId() == castOther.getAgreementId())
				&& (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAgreementId();
		result = 37 * result + this.getId();
		return result;
	}

}
