package com.scholastic.sbam.server.database.codegen;

// Generated Mar 7, 2011 3:54:30 PM by Hibernate Tools 3.2.4.GA

/**
 * AgreementSiteId generated by hbm2java
 */
public class AgreementSiteId implements java.io.Serializable {

	private int agreementId;
	private int siteUcn;
	private int siteUcnSuffix;

	public AgreementSiteId() {
	}

	public AgreementSiteId(int agreementId, int siteUcn, int siteUcnSuffix) {
		this.agreementId = agreementId;
		this.siteUcn = siteUcn;
		this.siteUcnSuffix = siteUcnSuffix;
	}

	public int getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(int agreementId) {
		this.agreementId = agreementId;
	}

	public int getSiteUcn() {
		return this.siteUcn;
	}

	public void setSiteUcn(int siteUcn) {
		this.siteUcn = siteUcn;
	}

	public int getSiteUcnSuffix() {
		return this.siteUcnSuffix;
	}

	public void setSiteUcnSuffix(int siteUcnSuffix) {
		this.siteUcnSuffix = siteUcnSuffix;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgreementSiteId))
			return false;
		AgreementSiteId castOther = (AgreementSiteId) other;

		return (this.getAgreementId() == castOther.getAgreementId())
				&& (this.getSiteUcn() == castOther.getSiteUcn())
				&& (this.getSiteUcnSuffix() == castOther.getSiteUcnSuffix());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAgreementId();
		result = 37 * result + this.getSiteUcn();
		result = 37 * result + this.getSiteUcnSuffix();
		return result;
	}

}
