package com.scholastic.sbam.server.database.codegen;

// Generated Jun 23, 2011 2:41:16 PM by Hibernate Tools 3.2.4.GA

/**
 * AlienInstitution generated by hbm2java
 */
public class AlienInstitution implements java.io.Serializable {

	private AlienInstitutionId id;

	public AlienInstitution() {
	}

	public AlienInstitution(AlienInstitutionId id) {
		this.id = id;
	}

	public AlienInstitutionId getId() {
		return this.id;
	}

	public void setId(AlienInstitutionId id) {
		this.id = id;
	}

}
