package com.scholastic.sbam.server.database.codegen;

// Generated Feb 25, 2011 10:26:02 AM by Hibernate Tools 3.2.4.GA

/**
 * AuthIpId generated by hbm2java
 */
public class AuthIpId implements java.io.Serializable {

	private int agreementId;
	private int siteUcn;
	private String siteLocCode;
	private int ipFrom;

	public AuthIpId() {
	}

	public AuthIpId(int agreementId, int siteUcn, String siteLocCode, int ipFrom) {
		this.agreementId = agreementId;
		this.siteUcn = siteUcn;
		this.siteLocCode = siteLocCode;
		this.ipFrom = ipFrom;
	}

	public int getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(int agreementId) {
		this.agreementId = agreementId;
	}

	public int getSiteUcn() {
		return this.siteUcn;
	}

	public void setSiteUcn(int siteUcn) {
		this.siteUcn = siteUcn;
	}

	public String getSiteLocCode() {
		return this.siteLocCode;
	}

	public void setSiteLocCode(String siteLocCode) {
		this.siteLocCode = siteLocCode;
	}

	public int getIpFrom() {
		return this.ipFrom;
	}

	public void setIpFrom(int ipFrom) {
		this.ipFrom = ipFrom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthIpId))
			return false;
		AuthIpId castOther = (AuthIpId) other;

		return (this.getAgreementId() == castOther.getAgreementId())
				&& (this.getSiteUcn() == castOther.getSiteUcn())
				&& ((this.getSiteLocCode() == castOther.getSiteLocCode()) || (this
						.getSiteLocCode() != null
						&& castOther.getSiteLocCode() != null && this
						.getSiteLocCode().equals(castOther.getSiteLocCode())))
				&& (this.getIpFrom() == castOther.getIpFrom());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAgreementId();
		result = 37 * result + this.getSiteUcn();
		result = 37
				* result
				+ (getSiteLocCode() == null ? 0 : this.getSiteLocCode()
						.hashCode());
		result = 37 * result + this.getIpFrom();
		return result;
	}

}
