package com.scholastic.sbam.server.database.codegen;

// Generated Apr 9, 2011 12:47:53 PM by Hibernate Tools 3.2.4.GA

/**
 * ContactId generated by hbm2java
 */
public class ContactId implements java.io.Serializable {

	private int contactId;
	private String address2;

	public ContactId() {
	}

	public ContactId(int contactId, String address2) {
		this.contactId = contactId;
		this.address2 = address2;
	}

	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactId))
			return false;
		ContactId castOther = (ContactId) other;

		return (this.getContactId() == castOther.getContactId())
				&& ((this.getAddress2() == castOther.getAddress2()) || (this
						.getAddress2() != null
						&& castOther.getAddress2() != null && this
						.getAddress2().equals(castOther.getAddress2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContactId();
		result = 37 * result
				+ (getAddress2() == null ? 0 : this.getAddress2().hashCode());
		return result;
	}

}
