package com.scholastic.sbam.server.database.codegen;

// Generated Feb 20, 2011 11:36:37 AM by Hibernate Tools 3.2.4.GA

/**
 * InstitutionId generated by hbm2java
 */
public class InstitutionId implements java.io.Serializable {

	private int ucn;
	private int seq;

	public InstitutionId() {
	}

	public InstitutionId(int ucn, int seq) {
		this.ucn = ucn;
		this.seq = seq;
	}

	public int getUcn() {
		return this.ucn;
	}

	public void setUcn(int ucn) {
		this.ucn = ucn;
	}

	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InstitutionId))
			return false;
		InstitutionId castOther = (InstitutionId) other;

		return (this.getUcn() == castOther.getUcn())
				&& (this.getSeq() == castOther.getSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUcn();
		result = 37 * result + this.getSeq();
		return result;
	}

}
