package com.scholastic.sbam.server.database.codegen;

// Generated Aug 1, 2011 6:30:58 PM by Hibernate Tools 3.2.4.GA

/**
 * InstitutionState generated by hbm2java
 */
public class InstitutionState implements java.io.Serializable {

	private String stateCode;
	private String description;
	private String countryCode;

	public InstitutionState() {
	}

	public InstitutionState(String stateCode, String description,
			String countryCode) {
		this.stateCode = stateCode;
		this.description = description;
		this.countryCode = countryCode;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

}
