package com.scholastic.sbam.server.database.codegen;

// Generated Apr 11, 2011 11:14:19 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * RemoteUrl generated by hbm2java
 */
public class RemoteUrl implements java.io.Serializable {

	private RemoteUrlId id;
	private char approved;
	private char activated;
	private String note;
	private String orgPath;
	private Date createdDatetime;
	private char status;

	public RemoteUrl() {
	}

	public RemoteUrl(RemoteUrlId id, char approved, char activated,
			String note, String orgPath, Date createdDatetime, char status) {
		this.id = id;
		this.approved = approved;
		this.activated = activated;
		this.note = note;
		this.orgPath = orgPath;
		this.createdDatetime = createdDatetime;
		this.status = status;
	}

	public RemoteUrlId getId() {
		return this.id;
	}

	public void setId(RemoteUrlId id) {
		this.id = id;
	}

	public char getApproved() {
		return this.approved;
	}

	public void setApproved(char approved) {
		this.approved = approved;
	}

	public char getActivated() {
		return this.activated;
	}

	public void setActivated(char activated) {
		this.activated = activated;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getOrgPath() {
		return this.orgPath;
	}

	public void setOrgPath(String orgPath) {
		this.orgPath = orgPath;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
