package com.scholastic.sbam.server.database.codegen;

// Generated Aug 1, 2011 6:30:58 PM by Hibernate Tools 3.2.4.GA

/**
 * SnapshotProductService generated by hbm2java
 */
public class SnapshotProductService implements java.io.Serializable {

	private SnapshotProductServiceId id;

	public SnapshotProductService() {
	}

	public SnapshotProductService(SnapshotProductServiceId id) {
		this.id = id;
	}

	public SnapshotProductServiceId getId() {
		return this.id;
	}

	public void setId(SnapshotProductServiceId id) {
		this.id = id;
	}

}
