package com.scholastic.sbam.server.database.codegen;

// Generated Jul 14, 2011 10:05:06 PM by Hibernate Tools 3.2.4.GA

/**
 * SnapshotProductServiceId generated by hbm2java
 */
public class SnapshotProductServiceId implements java.io.Serializable {

	private int snapshotId;
	private String productServiceCode;

	public SnapshotProductServiceId() {
	}

	public SnapshotProductServiceId(int snapshotId, String productServiceCode) {
		this.snapshotId = snapshotId;
		this.productServiceCode = productServiceCode;
	}

	public int getSnapshotId() {
		return this.snapshotId;
	}

	public void setSnapshotId(int snapshotId) {
		this.snapshotId = snapshotId;
	}

	public String getProductServiceCode() {
		return this.productServiceCode;
	}

	public void setProductServiceCode(String productServiceCode) {
		this.productServiceCode = productServiceCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SnapshotProductServiceId))
			return false;
		SnapshotProductServiceId castOther = (SnapshotProductServiceId) other;

		return (this.getSnapshotId() == castOther.getSnapshotId())
				&& ((this.getProductServiceCode() == castOther
						.getProductServiceCode()) || (this
						.getProductServiceCode() != null
						&& castOther.getProductServiceCode() != null && this
						.getProductServiceCode().equals(
								castOther.getProductServiceCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSnapshotId();
		result = 37
				* result
				+ (getProductServiceCode() == null ? 0 : this
						.getProductServiceCode().hashCode());
		return result;
	}

}
