package com.scholastic.sbam.server.database.codegen;

// Generated Jun 28, 2011 11:14:17 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Snapshot generated by hbm2java
 */
public class Snapshot implements java.io.Serializable {

	private String snapshotCode;
	private String snapshotName;
	private String snapshotType;
	private char productServiceType;
	private Date snapshotTaken;
	private Date createdDatetime;
	private char status;

	public Snapshot() {
	}

	public Snapshot(String snapshotCode, String snapshotName,
			String snapshotType, char productServiceType, Date createdDatetime,
			char status) {
		this.snapshotCode = snapshotCode;
		this.snapshotName = snapshotName;
		this.snapshotType = snapshotType;
		this.productServiceType = productServiceType;
		this.createdDatetime = createdDatetime;
		this.status = status;
	}

	public Snapshot(String snapshotCode, String snapshotName,
			String snapshotType, char productServiceType, Date snapshotTaken,
			Date createdDatetime, char status) {
		this.snapshotCode = snapshotCode;
		this.snapshotName = snapshotName;
		this.snapshotType = snapshotType;
		this.productServiceType = productServiceType;
		this.snapshotTaken = snapshotTaken;
		this.createdDatetime = createdDatetime;
		this.status = status;
	}

	public String getSnapshotCode() {
		return this.snapshotCode;
	}

	public void setSnapshotCode(String snapshotCode) {
		this.snapshotCode = snapshotCode;
	}

	public String getSnapshotName() {
		return this.snapshotName;
	}

	public void setSnapshotName(String snapshotName) {
		this.snapshotName = snapshotName;
	}

	public String getSnapshotType() {
		return this.snapshotType;
	}

	public void setSnapshotType(String snapshotType) {
		this.snapshotType = snapshotType;
	}

	public char getProductServiceType() {
		return this.productServiceType;
	}

	public void setProductServiceType(char productServiceType) {
		this.productServiceType = productServiceType;
	}

	public Date getSnapshotTaken() {
		return this.snapshotTaken;
	}

	public void setSnapshotTaken(Date snapshotTaken) {
		this.snapshotTaken = snapshotTaken;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
