package com.scholastic.sbam.server.database.codegen;

// Generated Jun 28, 2011 11:14:17 AM by Hibernate Tools 3.2.4.GA

/**
 * SnapshotProductServiceId generated by hbm2java
 */
public class SnapshotProductServiceId implements java.io.Serializable {

	private String snapshotCode;
	private String productServiceCode;

	public SnapshotProductServiceId() {
	}

	public SnapshotProductServiceId(String snapshotCode,
			String productServiceCode) {
		this.snapshotCode = snapshotCode;
		this.productServiceCode = productServiceCode;
	}

	public String getSnapshotCode() {
		return this.snapshotCode;
	}

	public void setSnapshotCode(String snapshotCode) {
		this.snapshotCode = snapshotCode;
	}

	public String getProductServiceCode() {
		return this.productServiceCode;
	}

	public void setProductServiceCode(String productServiceCode) {
		this.productServiceCode = productServiceCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SnapshotProductServiceId))
			return false;
		SnapshotProductServiceId castOther = (SnapshotProductServiceId) other;

		return ((this.getSnapshotCode() == castOther.getSnapshotCode()) || (this
				.getSnapshotCode() != null
				&& castOther.getSnapshotCode() != null && this
				.getSnapshotCode().equals(castOther.getSnapshotCode())))
				&& ((this.getProductServiceCode() == castOther
						.getProductServiceCode()) || (this
						.getProductServiceCode() != null
						&& castOther.getProductServiceCode() != null && this
						.getProductServiceCode().equals(
								castOther.getProductServiceCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSnapshotCode() == null ? 0 : this.getSnapshotCode()
						.hashCode());
		result = 37
				* result
				+ (getProductServiceCode() == null ? 0 : this
						.getProductServiceCode().hashCode());
		return result;
	}

}
