package com.scholastic.sbam.server.database.codegen;

// Generated Jul 28, 2011 1:20:31 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * SnapshotTermData generated by hbm2java
 */
public class SnapshotTermData implements java.io.Serializable {

	private SnapshotTermDataId id;
	private Date startDate;
	private Date endDate;
	private Date terminateDate;
	private String termType;
	private String cancelReasonCode;
	private Date cancelDate;
	private BigDecimal dollarValue;
	private int workstations;
	private int buildings;
	private int population;
	private int enrollment;
	private String commissionCode;
	private char primaryTerm;
	private BigDecimal serviceFraction;
	private BigDecimal customerFraction;

	public SnapshotTermData() {
	}

	public SnapshotTermData(SnapshotTermDataId id, String termType,
			String cancelReasonCode, BigDecimal dollarValue, int workstations,
			int buildings, int population, int enrollment,
			String commissionCode, char primaryTerm,
			BigDecimal serviceFraction, BigDecimal customerFraction) {
		this.id = id;
		this.termType = termType;
		this.cancelReasonCode = cancelReasonCode;
		this.dollarValue = dollarValue;
		this.workstations = workstations;
		this.buildings = buildings;
		this.population = population;
		this.enrollment = enrollment;
		this.commissionCode = commissionCode;
		this.primaryTerm = primaryTerm;
		this.serviceFraction = serviceFraction;
		this.customerFraction = customerFraction;
	}

	public SnapshotTermData(SnapshotTermDataId id, Date startDate,
			Date endDate, Date terminateDate, String termType,
			String cancelReasonCode, Date cancelDate, BigDecimal dollarValue,
			int workstations, int buildings, int population, int enrollment,
			String commissionCode, char primaryTerm,
			BigDecimal serviceFraction, BigDecimal customerFraction) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
		this.terminateDate = terminateDate;
		this.termType = termType;
		this.cancelReasonCode = cancelReasonCode;
		this.cancelDate = cancelDate;
		this.dollarValue = dollarValue;
		this.workstations = workstations;
		this.buildings = buildings;
		this.population = population;
		this.enrollment = enrollment;
		this.commissionCode = commissionCode;
		this.primaryTerm = primaryTerm;
		this.serviceFraction = serviceFraction;
		this.customerFraction = customerFraction;
	}

	public SnapshotTermDataId getId() {
		return this.id;
	}

	public void setId(SnapshotTermDataId id) {
		this.id = id;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getTerminateDate() {
		return this.terminateDate;
	}

	public void setTerminateDate(Date terminateDate) {
		this.terminateDate = terminateDate;
	}

	public String getTermType() {
		return this.termType;
	}

	public void setTermType(String termType) {
		this.termType = termType;
	}

	public String getCancelReasonCode() {
		return this.cancelReasonCode;
	}

	public void setCancelReasonCode(String cancelReasonCode) {
		this.cancelReasonCode = cancelReasonCode;
	}

	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}

	public BigDecimal getDollarValue() {
		return this.dollarValue;
	}

	public void setDollarValue(BigDecimal dollarValue) {
		this.dollarValue = dollarValue;
	}

	public int getWorkstations() {
		return this.workstations;
	}

	public void setWorkstations(int workstations) {
		this.workstations = workstations;
	}

	public int getBuildings() {
		return this.buildings;
	}

	public void setBuildings(int buildings) {
		this.buildings = buildings;
	}

	public int getPopulation() {
		return this.population;
	}

	public void setPopulation(int population) {
		this.population = population;
	}

	public int getEnrollment() {
		return this.enrollment;
	}

	public void setEnrollment(int enrollment) {
		this.enrollment = enrollment;
	}

	public String getCommissionCode() {
		return this.commissionCode;
	}

	public void setCommissionCode(String commissionCode) {
		this.commissionCode = commissionCode;
	}

	public char getPrimaryTerm() {
		return this.primaryTerm;
	}

	public void setPrimaryTerm(char primaryTerm) {
		this.primaryTerm = primaryTerm;
	}

	public BigDecimal getServiceFraction() {
		return this.serviceFraction;
	}

	public void setServiceFraction(BigDecimal serviceFraction) {
		this.serviceFraction = serviceFraction;
	}

	public BigDecimal getCustomerFraction() {
		return this.customerFraction;
	}

	public void setCustomerFraction(BigDecimal customerFraction) {
		this.customerFraction = customerFraction;
	}

}
