package com.scholastic.sbam.server.database.codegen;

// Generated Jun 16, 2011 5:48:55 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * StatsAdmin generated by hbm2java
 */
public class StatsAdmin implements java.io.Serializable {

	private int ucn;
	private String adminUid;
	private String adminPassword;
	private String statsGroup;
	private String note;
	private Date createdDatetime;
	private char status;

	public StatsAdmin() {
	}

	public StatsAdmin(int ucn, String adminUid, String adminPassword,
			String statsGroup, String note, Date createdDatetime, char status) {
		this.ucn = ucn;
		this.adminUid = adminUid;
		this.adminPassword = adminPassword;
		this.statsGroup = statsGroup;
		this.note = note;
		this.createdDatetime = createdDatetime;
		this.status = status;
	}

	public int getUcn() {
		return this.ucn;
	}

	public void setUcn(int ucn) {
		this.ucn = ucn;
	}

	public String getAdminUid() {
		return this.adminUid;
	}

	public void setAdminUid(String adminUid) {
		this.adminUid = adminUid;
	}

	public String getAdminPassword() {
		return this.adminPassword;
	}

	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	public String getStatsGroup() {
		return this.statsGroup;
	}

	public void setStatsGroup(String statsGroup) {
		this.statsGroup = statsGroup;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreatedDatetime() {
		return this.createdDatetime;
	}

	public void setCreatedDatetime(Date createdDatetime) {
		this.createdDatetime = createdDatetime;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
