package com.scholastic.sbam.server.database.codegen;

// Generated Mar 4, 2011 3:03:09 PM by Hibernate Tools 3.2.4.GA

/**
 * UcnConversionId generated by hbm2java
 */
public class UcnConversionId implements java.io.Serializable {

	private int ucn;
	private int ucnConversionSuffix;

	public UcnConversionId() {
	}

	public UcnConversionId(int ucn, int ucnConversionSuffix) {
		this.ucn = ucn;
		this.ucnConversionSuffix = ucnConversionSuffix;
	}

	public int getUcn() {
		return this.ucn;
	}

	public void setUcn(int ucn) {
		this.ucn = ucn;
	}

	public int getUcnConversionSuffix() {
		return this.ucnConversionSuffix;
	}

	public void setUcnConversionSuffix(int ucnConversionSuffix) {
		this.ucnConversionSuffix = ucnConversionSuffix;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UcnConversionId))
			return false;
		UcnConversionId castOther = (UcnConversionId) other;

		return (this.getUcn() == castOther.getUcn())
				&& (this.getUcnConversionSuffix() == castOther
						.getUcnConversionSuffix());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUcn();
		result = 37 * result + this.getUcnConversionSuffix();
		return result;
	}

}
