package com.scholastic.sbam.server.database.codegen;

// Generated Dec 14, 2010 11:47:18 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UserMessage generated by hbm2java
 */
public class UserMessage implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String locationTag;
	private int windowPosX;
	private int windowPosY;
	private int windowPosZ;
	private int windowWidth;
	private int windowHeight;
	private String text;
	private Date createDate;
	private char status;

	public UserMessage() {
	}

	public UserMessage(String userName, String locationTag, int windowPosX,
			int windowPosY, int windowPosZ, int windowWidth, int windowHeight,
			String text, Date createDate, char status) {
		this.userName = userName;
		this.locationTag = locationTag;
		this.windowPosX = windowPosX;
		this.windowPosY = windowPosY;
		this.windowPosZ = windowPosZ;
		this.windowWidth = windowWidth;
		this.windowHeight = windowHeight;
		this.text = text;
		this.createDate = createDate;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLocationTag() {
		return this.locationTag;
	}

	public void setLocationTag(String locationTag) {
		this.locationTag = locationTag;
	}

	public int getWindowPosX() {
		return this.windowPosX;
	}

	public void setWindowPosX(int windowPosX) {
		this.windowPosX = windowPosX;
	}

	public int getWindowPosY() {
		return this.windowPosY;
	}

	public void setWindowPosY(int windowPosY) {
		this.windowPosY = windowPosY;
	}

	public int getWindowPosZ() {
		return this.windowPosZ;
	}

	public void setWindowPosZ(int windowPosZ) {
		this.windowPosZ = windowPosZ;
	}

	public int getWindowWidth() {
		return this.windowWidth;
	}

	public void setWindowWidth(int windowWidth) {
		this.windowWidth = windowWidth;
	}

	public int getWindowHeight() {
		return this.windowHeight;
	}

	public void setWindowHeight(int windowHeight) {
		this.windowHeight = windowHeight;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
