package com.scholastic.sbam.server.database.codegen;

// Generated Mar 11, 2011 8:38:10 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * UserCache generated by hbm2java
 */
public class UserCache implements java.io.Serializable {

	private UserCacheId id;
	private Date accessDatetime;
	private int restoreColumn;
	private int restoreRow;
	private char restoreState;

	public UserCache() {
	}

	public UserCache(UserCacheId id, Date accessDatetime, int restoreColumn,
			int restoreRow, char restoreState) {
		this.id = id;
		this.accessDatetime = accessDatetime;
		this.restoreColumn = restoreColumn;
		this.restoreRow = restoreRow;
		this.restoreState = restoreState;
	}

	public UserCacheId getId() {
		return this.id;
	}

	public void setId(UserCacheId id) {
		this.id = id;
	}

	public Date getAccessDatetime() {
		return this.accessDatetime;
	}

	public void setAccessDatetime(Date accessDatetime) {
		this.accessDatetime = accessDatetime;
	}

	public int getRestoreColumn() {
		return this.restoreColumn;
	}

	public void setRestoreColumn(int restoreColumn) {
		this.restoreColumn = restoreColumn;
	}

	public int getRestoreRow() {
		return this.restoreRow;
	}

	public void setRestoreRow(int restoreRow) {
		this.restoreRow = restoreRow;
	}

	public char getRestoreState() {
		return this.restoreState;
	}

	public void setRestoreState(char restoreState) {
		this.restoreState = restoreState;
	}

}
