package com.scholastic.sbam.server.database.codegen;

// Generated Jan 19, 2011 12:27:01 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * WelcomeMessage generated by hbm2java
 */
public class WelcomeMessage implements java.io.Serializable {

	private Integer id;
	private Date postDate;
	private String title;
	private String content;
	private Date expireDate;
	private char deleted;

	public WelcomeMessage() {
	}

	public WelcomeMessage(Date postDate, String title, String content,
			Date expireDate, char deleted) {
		this.postDate = postDate;
		this.title = title;
		this.content = content;
		this.expireDate = expireDate;
		this.deleted = deleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	public char getDeleted() {
		return this.deleted;
	}

	public void setDeleted(char deleted) {
		this.deleted = deleted;
	}

}
